CREATE TABLE users (
  username TEXT PRIMARY KEY,
  mail TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  name TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  modified_at TIMESTAMP WITH TIME ZONE,
  verification_token TEXT,
  verification_token_valid_until TIMESTAMP WITH TIME ZONE,
  verified_at TIMESTAMP WITH TIME ZONE,
  password_reset_token TEXT,
  password_reset_token_valid_until TIMESTAMP WITH TIME ZONE,
  password_invalidated BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'inactive',
  account_type TEXT NOT NULL DEFAULT 'user'
);

CREATE TABLE config (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL
);

INSERT INTO config(key, value) VALUES ('setupCompleted', 'false'::JSONB);

CREATE TABLE jobs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  pipeline_id TEXT NOT NULL,
  runner_id INT NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  blueprint JSONB NOT NULL,
  logs JSONB,
  metrics JSONB,
  status TEXT NOT NULL DEFAULT 'created',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  started_by TEXT,
  current_phase INT,
  test_run BOOLEAN NOT NULL DEFAULT false,
  variables JSONB,
  working_dir TEXT,
  sentinel_value TEXT,
  priority SMALLINT default 4 NOT NULL
);

CREATE TABLE pipelines (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  blueprint JSONB,
  runner_id INT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_by TEXT NOT NULL,
  modified_at TIMESTAMP WITH TIME ZONE,
  modified_by TEXT,
  variables JSONB,
  working_dir TEXT,
  priority SMALLINT NOT NULL DEFAULT 4,
  archived BOOLEAN default false
);

CREATE TABLE pipeline_schedules(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pipeline_id TEXT NOT NULL,
  cron_expression TEXT,
  cron_readable TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_by TEXT NOT NULL,
  modified_at TIMESTAMP WITH TIME ZONE,
  modified_by TEXT,
  next_run TIMESTAMP WITH TIME ZONE
);

CREATE TABLE runners (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  token TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'inactive',
  last_run TIMESTAMP WITH TIME ZONE,
  jobs_run INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_by TEXT NOT NULL,
  modified_at TIMESTAMP WITH TIME ZONE,
  modified_by TEXT,
  params JSONB
);

CREATE TABLE mail_queue (
    mail_address text not null,
    mail_type_id text not null,
    message jsonb not null,
    status text not null,
    status_msg text,
    priority integer not null,
    processed_count integer not null default 0,
    created_at timestamp with time zone not null,
    status_changed_at timestamp with time zone,
    primary key (mail_address, mail_type_id)
);

CREATE TABLE records (
	id text NOT NULL,
	"source" text NOT NULL,
	created timestamptz NOT NULL,
	title text NOT NULL,
	contributors jsonb NULL,
	publication_date _int2 NULL,
	access_options jsonb NULL,
	identifiers jsonb NULL,
	CONSTRAINT records_pkey PRIMARY KEY (id)
);
